version: "2"

services:

  redis:
    image: redis:3
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data:rw
    restart: always

  postgres:
    image: postgres:9.6.4
    env_file:
      - .env_postgres
    ports:
      - '5432:5432'
    volumes:
      - './postgres:/var/lib/postgresql/data/'
    restart: always

  rabbitmq:
    image: rabbitmq:3.6
    ports:
      - "5672:5672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq:rw
    restart: always

